import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

const store = new Vuex.Store({
	state: {
		iconlib:[
			{
				iconname:'唱歌',
				url:'changge.png',
				isselect:true,
				targetdays:1,
				jiyu:'哆唻咪发嗖拉嘻'
			},
			{
				iconname:'晨练',
				url:'chenlian.png',
				isselect:false,
				targetdays:2,
				jiyu:'早起的鸟的有虫吃！！！'
			},
			{
				iconname:'跑步',
				url:'paobu.png',
				isselect:false,
				targetdays:21,
				jiyu:'身体健康，万事如意！'
			},
			{
				iconname:'吃早餐',
				url:'chizaocan.png',
				isselect:false,
				targetdays:4,
				jiyu:'不吃早餐胖100斤！！！'
			},
			{
				iconname:'画画',
				url:'huahua.png',
				isselect:false,
				targetdays:21,
				jiyu:'画一个姑娘陪着我'
			},
			{
				iconname:'多喝烫水',
				url:'duohetangshui.png',
				isselect:false,
				targetdays:21,
				jiyu:'多喝烫水o~'
			},
			{
				iconname:'与家人通话',
				url:'yujiarentonghua.png',
				isselect:false,
				targetdays:21,
				jiyu:'常给爸妈打个电话'
			},
			{
				iconname:'减肥',
				url:'jianfei.png',
				isselect:false,
				targetdays:21,
				jiyu:'不减100斤不睡觉！'
			},
			{
				iconname:'健身',
				url:'jianshen.png',
				isselect:false,
				targetdays:21,
				jiyu:'新一代彭于晏'
			},
			{
				iconname:'戒酒',
				url:'jiejiu.png',
				isselect:false,
				targetdays:21,
				jiyu:'吸酒有害健康！'
			},
			{
				iconname:'戒烟',
				url:'jieyan.png',
				isselect:false,
				targetdays:21,
				jiyu:'喝烟有害健康！'
			},
			{
				iconname:'看书',
				url:'kanshu.png',
				isselect:false,
				targetdays:21,
				jiyu:'文青在路上~'
			},
			{
				iconname:'学习',
				url:'xuexi.png',
				isselect:false,
				targetdays:21,
				jiyu:'学习使我快乐！'
			},
			{
				iconname:'看电影',
				url:'kandianying.png',
				isselect:false,
				targetdays:21,
				jiyu:'强推猩球崛起！'
			},
			{
				iconname:'微笑',
				url:'weixiao.png',
				isselect:false,
				targetdays:21,
				jiyu:'笑一笑,十年笑'
			},
			{
				iconname:'吉他',
				url:'jita.png',
				isselect:false,
				targetdays:21,
				jiyu:'想听你弹吉他'
			},
			{
				iconname:'练字',
				url:'lianzi.png',
				isselect:false,
				targetdays:21,
				jiyu:'写得一手好字啊'
			},
			{
				iconname:'吃蔬菜',
				url:'chishucai.png',
				isselect:false,
				targetdays:3,
				jiyu:'别光喝啊，吃菜！'
			},
			{
				iconname:'理财',
				url:'licai.png',
				isselect:false,
				targetdays:21,
				jiyu:'如果有一天我变得很有钱~'
			},
			{
				iconname:'练钢琴',
				url:'liangangqin.png',
				isselect:false,
				targetdays:21,
				jiyu:'想听你弹钢琴'
			},
			{
				iconname:'陪孩子',
				url:'peihaizi.png',
				isselect:false,
				targetdays:21,
				jiyu:'从小我的妈妈告诉我穷人家的孩子早当家—王晗旭'
			},
			{
				iconname:'篮球',
				url:'lanqiu.png',
				isselect:false,
				targetdays:21,
				jiyu:'想看你打篮球'
			},
			{
				iconname:'摄影',
				url:'sheying.png',
				isselect:false,
				targetdays:21,
				jiyu:'美！'
			},
			{
				iconname:'刷牙',
				url:'shuaya.png',
				isselect:false,
				targetdays:21,
				jiyu:'洗漱漱洗漱漱，欧欧'
			},
			{
				iconname:'听歌',
				url:'tingge.png',
				isselect:false,
				targetdays:21,
				jiyu:'打个中国结，在几个红腰带'
			},
			{
				iconname:'滑板',
				url:'huaban.png',
				isselect:false,
				targetdays:21,
				jiyu:'好酷的'
			},
			{
				iconname:'英语',
				url:'yingyu.png',
				isselect:false,
				targetdays:21,
				jiyu:'四六级，冲！'
			},
			{
				iconname:'早起',
				url:'zaoqi.png',
				isselect:false,
				targetdays:21,
				jiyu:'早起早睡，方能养生'
			},
			{
				iconname:'早睡',
				url:'zaoshui.png',
				isselect:false,
				targetdays:21,
				jiyu:'早睡早起，方能养生'
			},
			{
				iconname:'做饭',
				url:'zuofan.png',
				isselect:false,
				targetdays:21,
				jiyu:'真香！'
			},
		],
		houmendata:1
	}
})

export default store
